
from playwright.sync_api import sync_playwright, expect
import os
import time

def run(playwright):
    browser = playwright.chromium.launch(headless=True)
    context = browser.new_context(viewport={'width': 1920, 'height': 1080})
    page = context.new_page()

    try:
        # Navigate to the app
        page.goto("http://localhost:5173/")

        # Wait for loading
        page.wait_for_load_state('networkidle')

        # The sidebar class might be generated by CSS modules.
        # But we can try to find the sidebar by looking for the "navLink" elements or the container.
        # Or we can bypass the sidebar hover and just goto the URL directly,
        # but typical SPA navigation via link is better to test integration.

        # Let's try to expand sidebar by hovering near left edge or finding the container by text "R" (the collapsed header).

        # Find header "R"
        page.get_by_text("Remis", exact=False).first.hover()

        # Wait for expansion
        time.sleep(0.5)

        # Now text should be visible
        # Click Glossary Manager
        # If this fails, we'll fallback to direct URL
        try:
            page.get_by_text("Glossary Manager").click()
        except:
            print("Sidebar navigation failed, trying direct URL")
            page.goto("http://localhost:5173/#/glossary-manager") # Hash router likely? Or history?
            # Looking at AppSider paths: '/glossary-manager'
            # If using HashRouter: /#/glossary-manager. If BrowserRouter: /glossary-manager
            # Let's try /glossary-manager first
            page.goto("http://localhost:5173/glossary-manager")


        # Wait for page to load
        # Check for title "Glossary Manager"
        expect(page.get_by_role("heading", name="Glossary Manager").first).to_be_visible(timeout=10000)

        # 3. Verify Search Options
        # Find the search input
        search_input = page.get_by_placeholder("Filter content...")
        expect(search_input).to_be_visible()

        time.sleep(2) # Give a moment for animations/fetches

        os.makedirs("/home/jules/verification", exist_ok=True)
        page.screenshot(path="/home/jules/verification/glossary_manager_layout.png")
        print("Screenshot captured.")

    except Exception as e:
        print(f"Verification failed: {e}")
        # Take failure screenshot
        page.screenshot(path="/home/jules/verification/failure.png")
    finally:
        browser.close()

with sync_playwright() as playwright:
    run(playwright)
