l_english:

 nz_environment.1.t:0 "A Britain of the South"
 nz_environment.1.d:0 "In order to bring some of the comforts of home to [ROOT.GetCountry.GetName], a number of [SCOPE.sCulture('scope_rabbits_english').GetName] settlers have been loosing rabbits, pigs, trout, and other animals into the wild in order to hunt them."
 nz_environment.1.d2:0 "In order to bring some of the comforts of home to New Zealand, a number of [SCOPE.sCulture('scope_rabbits_english').GetName] settlers have been loosing rabbits, pigs, trout, and other animals into the wild in order to hunt them."
 nz_environment.1.f:0 "#italic "Pursue these fearful creatures o'er the downs,\nAnd on thy well-breathed horse keep with thy hounds.\nAnd when thou hast on foot the purblind hare,\nMark the poor wretch, to overshoot his troubles\nHow he outruns the wind, and with what care\nHe cranks and crosses with a thousand doubles" #!"
 nz_environment.1.a:0 "How idyllic!"
 nz_environment.1.b:0 "We must put a stop to this."
 nz_containment_hunting_modifier:0 "Containment Hunting"

 nz_environment.2.t:0 "Rabbit Plague"
 nz_environment.2.d:0 "Hordes of grazing rabbits have stripped bare large expanses of pasture in [SCOPE.sState('crop_fail_state').GetName], outcompeting livestock for food and leaving the soil vulnerable to serious erosion."
 nz_environment.2.f:0 ""The man who introduced the rabbit to New Zealand was banqueted and lauded but they would hang him now, if they could get him. In England they fine a poacher, whereas he ought to be banished to New Zealand. New Zealand would pay his way and give him wages.""
 nz_environment.2.a:0 "It's going to be a bad year for farmers."
 nz_environment.2.b:0 "Fences, poison, whatever it takes, we need to get these rabbits under control."
 nz_modifier_rabbit_plague:0 "Rabbit Plague"
 nz_modifier_rabbit_plague_relief:0 "Rabbit Plague Relief"
 nz_modifier_rabbit_plague_relief_effect:0 "Mitigated Rabbit Plague"

 nz_environment.3.t:0 "Natural Enemies"
 nz_environment.3.d:0 "For all their efforts, no one has been able to halt the multiplication of the rabbit population in [ROOT.GetCountry.GetName]. With more rabbit plagues threatening to strike any day, many are turning their hopes to a controversial solution: importing weasels, stoats, and other predators to keep the conies in check."
 nz_environment.3.d2:0 "For all their efforts, no one has been able to halt the multiplication of the rabbit population in New Zealand. With more rabbit plagues threatening to strike any day, many are turning their hopes to a controversial solution: importing weasels, stoats, and other predators to keep the conies in check."
 nz_environment.3.f:0 "#italic "The Squatter went destroying in a different way to Cocky,\nHe said,'My land is rough in parts and very steep and rocky,\nI'll breed ferrets there at vast expense, buy cats at one-and-six,\nFor I think their 'natural enemies' should know the rabbit tricks." #!"
 nz_environment.3.a:0 "It's the only way."
 nz_environment.3.a.tt:0 "There might be no more rabbit plagues"
 nz_environment.3.b:0 "The remedy will be worse than the disease!"
 nz_environment.3.b.tt:0 "Rabbit plagues will continue"
 nz_modifier_importing_weasels:0 "Importing Mustelids"
 nz_natural_enemies_minus_2:0 "Not Addressing Rabbit Plagues"
 nz_natural_enemies_plus_2:0 "Addressing Rabbit Plagues"
 nz_natural_enemies_minus_1:0 "Not the Way"
 nz_natural_enemies_plus_1:0 "Not the Way"

 nz_environment.4.t:0 "Island Sanctuaries"

 nz_environment.5.t:0 "A Collector's Item"

 nz_environment.6.t:0 "The Preservation Act"

 nz_environment.7.t:0 "Island Sanctuaries"
 
 nz_environment.8.t:0 "The Last []"

 nz_environment.9.t:0 "From the Brink"